package io.github.jhipster.sample.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LabelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAllPropertiesEquals(Label expected, Label actual) {
        assertLabelAutoGeneratedPropertiesEquals(expected, actual);
        assertLabelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAllUpdatablePropertiesEquals(Label expected, Label actual) {
        assertLabelUpdatableFieldsEquals(expected, actual);
        assertLabelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelAutoGeneratedPropertiesEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelUpdatableFieldsEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLabelUpdatableRelationshipsEquals(Label expected, Label actual) {
        assertThat(actual)
            .as("Verify Label relationships")
            .satisfies(a -> assertThat(a.getOperations()).as("check operations").isEqualTo(expected.getOperations()));
    }
}
