# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstersampleapplication
services:
  app:
    image: jhipstersampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs,secret-samples
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipsterSampleApplication
      - SPRING_DATASOURCE_USERNAME=jhipsterSampleApplication
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/jhipsterSampleApplication
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8080; printf \"GET
          /management/health HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n\" >&3;
          grep -q \"\\\"status\\\":\\\"UP\\\"\" <&3'"
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
